default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] || "postgres" %>
  host: <%= ENV['POSTGRES_HOST'] || "localhost" %>

dev:
  <<: *default
  database: advocate_development

test:
  <<: *default
  database: advocate_test

prod:
  <<: *default
  database: advocate_production
  password: <%= ENV['POSTGRES_PASSWORD'] %>
