default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] || "postgres" %>
  host: <%= ENV['POSTGRES_HOST'] || "localhost" %>

dev:
  <<: *default
  database: advocate_development

test:
  <<: *default
  database: advocate_test

prod:
  <<: *default
  database: advocate_production
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 10
  connect_timeout: 2
  keepalives_idle: 30
  keepalives_interval: 10
  keepalives_count: 2
